[project]
name = "ai-seo-optimizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.0,<0.4.0",
    "langchain-google-genai>=2.0.0,<3.0.0",
    "google-generativeai>=0.7.0,<0.8.0",
    "python-dotenv>=1.0.0",
    "psycopg2-binary>=2.9.0",
    "markdown-it-py>=3.0.0,<4.0.0",
    "markdown>=3.9",
    "bs4>=0.0.2",
    "markdown-to-json>=2.1.2",
    "mdit-plain>=1.0.1",
]
